dist: trusty
sudo: required

language: cpp

matrix:
    include:
       - compiler: gcc
         addons:
             apt:
                 sources:
                     - ubuntu-toolchain-r-test
                 packages:
                     - g++-4.9
                     - gcc-4.9
         env: TRAVIS_CXX=g++-4.9 TRAVIS_CC=gcc-4.9 STRINGS=STD
       - compiler: gcc
         addons:
             apt:
                 sources:
                     - ubuntu-toolchain-r-test
                 packages:
                     - g++-4.9
                     - gcc-4.9
         env: TRAVIS_CXX=g++-4.9 TRAVIS_CC=gcc-4.9 STRINGS=ICU
       - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-5
                      - gcc-5
          env: TRAVIS_CXX=g++-5 TRAVIS_CC=gcc-5 STRINGS=STD
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-5
                      - gcc-5
          env: TRAVIS_CXX=g++-5 TRAVIS_CC=gcc-5 STRINGS=ICU

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-all-dev glib2.0-dev

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - GFSM_SRC="http://kaskade.dwds.de/~moocow/mirror/projects/gfsm"
    - |
        for pkg in gfsm-0.0.16-1 gfsmxl-0.0.15; do
            curl -O ${GFSM_SRC}/${pkg}.tar.gz
            tar xzf ${pkg}.tar.gz
            pushd ${pkg}
            CC=${TRAVIS_CC} CXX=${TRAVIS_CXX} ./configure && make && sudo make install
            popd
        done
    - cd ..

script:
    - mkdir build && cd build
    - cmake .. -DSTRING_IMPL=${STRINGS} -DWITH_PYTHON=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${TRAVIS_CXX} -DCMAKE_C_COMPILER=${TRAVIS_CC}
    - make VERBOSE=1 && make buildtests && make check && sudo make install

